baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Dorara 閱讀紀錄'
theme = ["PaperMod"]

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  [params.homeInfoParams]
    Title = "Hi there wave"
    Content = "關於科技，人性，存在"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardLineBreak = true