baseURL = 'https://blog.dorara.xyz/'
languageCode = 'en-us'
title = 'Dorara'
theme = ["PaperMod"]

[params]
  ShowReadingTime = true
  custom_css = ["css/custom.css"]

  [params.homeInfoParams]
    Title = "Hello World"
    Content = "關於科技，人性，存在"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardLineBreak = true